import jsPDF from "jspdf";
import type { TestSession } from "./types";
import type { Player } from "./types";
import { generateRecommendations } from "./sprintEngine";
import { isConnected, writeBinaryFile } from "./fsStorage";

export function exportTestPDF(test: TestSession, player: Player) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 50;

  doc.setFillColor(15, 20, 25);
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(190, 240, 90);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("SprintLab FV Pro", 40, 45);
  doc.setFontSize(11);
  doc.setTextColor(220, 230, 240);
  doc.text("Sprint & Force-Velocity Report", 40, 65);

  y = 120;
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`${player.firstName} ${player.lastName}`, 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y += 16;
  doc.text(
    `Mass: ${test.mass} kg   |   Date: ${new Date(test.createdAt).toLocaleString()}   |   Mode: ${test.inputMode}`,
    40,
    y
  );

  y += 30;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Force-Velocity Profile", 40, y);
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 20;

  const fv = test.analysis.fv;
  const rows: [string, string][] = [
    ["F0 (N)", fv.F0.toFixed(1)],
    ["F0 relative (N/kg)", (fv.F0_rel ?? 0).toFixed(2)],
    ["V0 (m/s)", fv.V0.toFixed(2)],
    ["Pmax (W)", fv.Pmax.toFixed(0)],
    ["Pmax relative (W/kg)", (fv.Pmax_rel ?? 0).toFixed(1)],
    ["Slope (N·s/m)", fv.slope.toFixed(2)],
    ["R²", fv.rSquared.toFixed(3)],
    ["Vmax measured (m/s)", test.analysis.vmax.toFixed(2)],
    ["Sprint duration (s)", test.analysis.duration.toFixed(2)],
    ["Distance covered (m)", test.analysis.distanceCovered.toFixed(1)],
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  rows.forEach(([k, v]) => {
    doc.text(k, 50, y);
    doc.text(v, 320, y);
    y += 16;
  });

  // Phases
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Sprint Phases", 40, y);
  y += 8;
  doc.line(40, y, W - 40, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  test.analysis.phases.forEach((p) => {
    const label =
      p.phase === "acceleration"
        ? "Acceleration"
        : p.phase === "max_velocity"
        ? "Max Velocity"
        : "Deceleration";
    doc.text(`• ${label}: ${p.startTime.toFixed(2)}s → ${p.endTime.toFixed(2)}s`, 50, y);
    y += 16;
  });

  // Recommendations
  const recs = generateRecommendations(fv, test.mass);
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Recommendations", 40, y);
  y += 8;
  doc.line(40, y, W - 40, y);
  y += 20;
  recs.forEach((r) => {
    if (y > 760) { doc.addPage(); y = 60; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(r.title, 50, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(r.detail, W - 100);
    lines.forEach((ln: string) => { doc.text(ln, 50, y); y += 14; });
    r.drills.forEach((d) => { doc.text(`  – ${d}`, 60, y); y += 14; });
    y += 8;
  });

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by SprintLab FV Pro", 40, doc.internal.pageSize.getHeight() - 24);

  doc.save(`SprintLab_${player.lastName}_${new Date(test.createdAt).toISOString().slice(0, 10)}.pdf`);
}
